apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-loyalty
spec:
  params:
    - default: ''
      description: Sonarqube server address
      name: sonar_server
      type: string
  resources:
    - name: loyalty-git
      type: git
    - name: event-image
      type: image
    - name: user-image
      type: image
    - name: ui-image
      type: image
  tasks:
    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-Dsonar.host.url=http://sonarqube:9000'
            - '-Dsonar.userHome=/tmp/sonar'
            - '-DskipITs'
            - '-Darguments=-DskipITs'
      resources:
        inputs:
          - name: source
            resource: loyalty-git
      runAfter:
        - sonarqube-scan
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-repo
          workspace: local-maven-repo
    - name: build-event
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_ARGS_APPEND
          value: '-pl :event-service -am package'
        - name: PATH_CONTEXT
          value: loyalty-app-backend/
      resources:
        inputs:
          - name: source
            resource: loyalty-git
        outputs:
          - name: image
            resource: event-image
      runAfter:
        - code-analysis
      taskRef:
        kind: Task
        name: s2i-java-8
    - name: build-user
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_ARGS_APPEND
          value: '-pl :user-service -am package'
        - name: PATH_CONTEXT
          value: loyalty-app-backend/
      resources:
        inputs:
          - name: source
            resource: loyalty-git
        outputs:
          - name: image
            resource: user-image
      runAfter:
        - code-analysis
      taskRef:
        kind: Task
        name: s2i-java-8
    - name: build-ui
      params:
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: loyalty-git
        outputs:
          - name: image
            resource: ui-image
      runAfter:
        - code-analysis
      taskRef:
        kind: Task
        name: s2i-nodejs
    - name: deploy-event
      params:
        - name: COMMANDS
          value: >
            oc apply -f
            https://raw.githubusercontent.com/IBM/loyalty/master/loyalty-app-backend/event-service/deployment.yaml
            -n example-loyalty
      runAfter:
        - build-event
      taskRef:
        kind: Task
        name: openshift-client
    - name: deploy-user
      params:
        - name: COMMANDS
          value: >
            oc apply -f
            https://raw.githubusercontent.com/IBM/loyalty/master/loyalty-app-backend/user-service/deployment.yaml
            -n example-loyalty
      runAfter:
        - build-user
      taskRef:
        kind: Task
        name: openshift-client
    - name: deploy-ui
      params:
        - name: COMMANDS
          value: >
            oc apply -f
            https://raw.githubusercontent.com/IBM/loyalty/master/deployment.yaml
            -n example-loyalty
      runAfter:
        - build-event
      taskRef:
        kind: Task
        name: openshift-client
    - name: sonarqube-scan
      params:
        - name: sonar_server
          value: >-
            https://sonarqube-loken-sonar.apps.shared-na4.na4.openshift.opentlc.com
      resources:
        inputs:
          - name: git-repo
            resource: loyalty-git
      taskRef:
        kind: Task
        name: sonarqube-scan
  workspaces:
    - name: local-maven-repo
