---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: loyalty-run-
spec:
  params:
    - name: sonar_server
      value: https://sonarqube-loken-sonar.apps.shared-na4.na4.openshift.opentlc.com
  pipelineRef:
    name: example-loyalty
  resources:
  - name: loyalty-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/lokendr/loyalty.git
  - name: event-image
    resourceSpec:
      type: image
      params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/loyalty-infra/event
  - name: user-image
    resourceSpec:
      type: image
      params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/loyalty-infra/user
  - name: ui-image
    resourceSpec:
      type: image
      params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/loyalty-infra/ui
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  serviceAccountName: pipeline
